version: '3'

services:

  react-service:
    image: node:16-alpine
    build:
      context: .
      dockerfile: react.dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    command: [ "sh", "start.sh" ]
